# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128, verbose_name='请求头')),
                ('parmary', models.CharField(max_length=64, null=True, verbose_name='url参数')),
                ('body', models.CharField(max_length=1024, null=True, verbose_name='请求body')),
                ('methor', models.IntegerField(choices=[(1, 'POST'), (2, 'GET'), (3, 'PUT'), (4, 'DELETE')], verbose_name='请求方法')),
            ],
        ),
        migrations.CreateModel(
            name='RunEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=32, verbose_name='主机环境')),
                ('username', models.CharField(max_length=32, verbose_name='管理员帐号')),
                ('passwrod', models.CharField(max_length=32, verbose_name='管理员密码')),
                ('appkey', models.CharField(max_length=32, verbose_name='appkey名称')),
            ],
        ),
        migrations.CreateModel(
            name='UrlManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(max_length=128, verbose_name='url名称')),
                ('func', models.CharField(max_length=32, verbose_name='类别名称')),
            ],
        ),
        migrations.AddField(
            model_name='apimanage',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.UrlManage', verbose_name='url地址'),
        ),
    ]
