# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runenv',
            name='passwrod',
        ),
        migrations.RemoveField(
            model_name='runenv',
            name='username',
        ),
        migrations.AddField(
            model_name='runenv',
            name='token',
            field=models.CharField(default='123456789', max_length=512, verbose_name='管理员帐号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apimanage',
            name='body',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='请求body'),
        ),
        migrations.AlterField(
            model_name='apimanage',
            name='parmary',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='url参数'),
        ),
    ]
