# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20181128_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimanage',
            name='apiname',
            field=models.CharField(default='users', max_length=32, verbose_name='接口功能'),
            preserve_default=False,
        ),
    ]
