# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_apimanage_apiname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='runenv',
            name='host',
            field=models.CharField(max_length=32, unique=True, verbose_name='主机环境'),
        ),
        migrations.AddField(
            model_name='start_test',
            name='hosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.RunEnv', verbose_name='运行的主机'),
        ),
    ]
