# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20181129_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=16, verbose_name='返回的状态码')),
                ('test_content', models.TextField(verbose_name='测试结果')),
                ('test_data', models.DateTimeField(verbose_name='最后执行时间')),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apitest.ApiManage', verbose_name='运行的主机')),
            ],
        ),
        migrations.RemoveField(
            model_name='start_test',
            name='api',
        ),
        migrations.RemoveField(
            model_name='start_test',
            name='hosts',
        ),
        migrations.DeleteModel(
            name='Start_test',
        ),
    ]
