# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20181130_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='api',
            field=models.CharField(max_length=32, unique=True, verbose_name='功能接口'),
        ),
    ]
