# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20181130_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_result',
            name='test_data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后执行时间'),
        ),
    ]
